### ISSUE TITLE
Información sobre URLs

### ISSUE THREAD

**Issue by benoffi7** [mercadopago/sdk-android#11]
public static final String DUMMY_MERCHANT_BASE_URL = "https://www.mercadopago.com";
    public static final String DUMMY_MERCHANT_GET_CUSTOMER_URI = "/checkout/examples/getCustomer";
    public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/checkout/examples/doPayment";

Que hace o que deberia hacer cada URL para ponerlo en la peticion

                ErrorHandlingCallAdapter.MyCall<Payment> call = MerchantServer.createPayment(MainActivity.this, DUMMY_MERCHANT_BASE_URL, DUMMY_MERCHANT_CREATE_PAYMENT_URI, payment);

Gracias!

**Comment by scirielli** [comment]
GET_CUSTOMER_URI:
Este metodo devuelve un objeto customer guardado por vos con anterioridad, para poder presentarle las tarjetas guardadas y darle una experiencia express. 
En este link: https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/customers-and-cards/
podes ver al principio cómo llamar a la api para obtener tu customer.
Lo que llamamos "merchantAccessToken" es algún dato en tu app que identifique al usuario actual y te sirva en tu servidor para saber quien es y buscarlo.

CREATE_PAYMENT_URI:
https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/charge-with-creditcard/android/
al final de este link podes ver un ejemplo del posteo en php. En este método también es importante hacer la validaciones pertinentes antes de crear el pago.

**Comment by scirielli** [comment]
Te paso también un link donde podes encontrar el código server-side de nuestros mocks para que los tomes como guías.

https://github.com/mercadopago/customcheckout-php-server
