### ISSUE TITLE
Retrofit2 Builder

### ISSUE THREAD

**Issue by yanctrindade** [mercadopago/sdk-android#12]
Whenever I try to open payment methods screen using api lower than 23 like Android 4.4.x, right after clicking on "step 1" from the sample app. It crashes with the error message "NoDefaultClassError Retrofit2.Builder" inside of MercadoCore Class. Its working only for Android 6.0 API 23.

**Comment by scirielli** [comment]
Hi, I tested the examples project on 10, 17, 19, 21, 22 and 23 versions and worked fine. Could you tell me your target/compile sdk version? Is it possible that you hitted the dex count threshold?

**Comment by yanctrindade** [comment]
Actually I found the problem, it was solved on another issue. Mercado Pago SDK uses RetroFit2 that for some reason has problems with some google services on gradle. I did the same on other issue that says to remove some google services from gradle. Magically everything works fine now. Thanks!
