### ISSUE TITLE
MerchantPayment don't have "payer" and "capture" fields

### ISSUE THREAD

**Issue by gustavorozolin** [mercadopago/sdk-android#15]
I was trying to use MerchantPayment to make Authorization and Capture, so I didnt find "payer" and "capture" fields in
sdk-android/sdk/src/main/java/com/mercadopago/model/MerchantPayment.java

in Paymant class I have  "payer" and "capture" fields but I dont have "cardToken" field.

sdk-android/sdk/src/main/java/com/mercadopago/model/Payment.java

Its a bug or am I using this wrong?

Thanks.

**Comment by scirielli** [comment]
Hi,
the merchantAccessToken is the representation of the payer in your app. Typically is the access token or credential you set after logging in.
About authorization and capture, i guess you should authorize when you call MerchantServer.createPayment(...), and then capture after certain event like stock verification. In most cases, capture is a server-side task.

Regards,
SC

**Comment by gustavorozolin** [comment]
Yes I know, 

But in https://github.com/mercadopago/sdk-android/blob/master/example/src/main/java/com/mercadopago/examples/utils/ExamplesUtils.java#L126
you create a MerchantPayment instace and send to your server.

Do I need to builder a new payment in serve-side with this information?

Thanks.

**Comment by scirielli** [comment]
Hi, did you replace the example server (DUMMY_MERCHANT_BASE_URL = "https://www.mercadopago.com" and DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/checkout/examples/doPayment") with your own server-side code?

If not, here you can find a PHP server example of how to create a payment:
https://github.com/mercadopago/customcheckout-php-server

**Comment by gustavorozolin** [comment]
Yes I did. So in my server side (java) I need to build payment json to send to MarcadoPago server, because "**MerchantPayment**" dont have all field that I need send. Did you understand my doubt?

Thanks

**Comment by gustavorozolin** [comment]
OK. I got it.

Thank's you a lot.
