### ISSUE TITLE
Error on MercadoPago.Build

### ISSUE THREAD

**Issue by vrunoa** [mercadopago/sdk-android#16]
Hey guys I keep getting an error when trying to build a MercadoPago instance,
```
java.lang.VerifyError: com/mercadopago/core/MercadoPago
at com.mercadopago.core.MercadoPago$Builder.build(MercadoPago.java:291)
```

The code is quite simple
```
public class MercadoPagoView extends PSBindableView implements Bindable{

    private final Consultation consultation;
    private final MercadoPago mercadoPago;

    public MercadoPagoView(Activity context, Consultation consultation) {
        super(context, R.layout.content_mercadopago);
        this.consultation = consultation;

        mercadoPago = new MercadoPago.Builder()
                .setContext((ElectronicPaymentActivity)context)
                .setPublicKey(Flavour.MERCADO_PAGO_PUBLIC_KEY)
                .build();
    }
}
```

and my gradle looks like this
```
compile 'com.squareup.retrofit2:retrofit:2.0.0'
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
compile 'com.squareup.picasso:picasso:2.5.2'
compile('com.mercadopago:android-sdk:0.9.16@aar') {
        transitive = true
        exclude group: 'com.squareup.retrofit2'
        exclude group: 'com.squareup.picasso'
}
```

Any idea what could be failing ?

**Comment by scirielli** [comment]
Hi!
I tested your example with this gradle:

    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile('com.mercadopago:android-sdk:0.9.16@aar')

and I got this error:

    java.lang.ClassNotFoundException: retrofit2.converter.gson.GsonConverterFactory

it seems that the GsonConverterFactory class is not present in beta3. If you use:

    compile 'com.squareup.retrofit2:converter-gson:2.0.0

it works. Do you really need to use beta3 in your project?

Regards,
SC

**Comment by vrunoa** [comment]
@scirielli thanks. I also have to add **logging-interceptor** and **okhttp-urlconnection**

```
compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'
compile 'com.squareup.retrofit2:retrofit:2.0.0'
compile 'com.squareup.retrofit2:converter-gson:2.0.0'
compile 'com.squareup.picasso:picasso:2.5.2'
compile('com.mercadopago:android-sdk:0.9.16@aar') {
     transitive = true
     exclude group: 'com.squareup.retrofit2'
}
```
