### ISSUE TITLE
invalid item unit_price

### ISSUE THREAD

**Issue by omnixsolutions** [mercadopago/sdk-android#18]
Estoy teniendo este problema a la hora de pagar con Tarjetas, invalid item unit_price, tengo implementado todo, me muestras todo el proceso pero a la hora de pagar me de ese mensaje, queria saber si me pueden ayudar a resolverlo, estoy probando con mis credenciales de Mercadopago.

**Comment by scirielli** [comment]
Hola,
te contesté en el otro issue. Entiendo que es lo mismo.
Espero tu respuesta.

Saludos,
SC

**Comment by omnixsolutions** [comment]
Disculpa en cual issue?

**Comment by Brunoandroid** [comment]
omnixsolutions,,,
Hi, did you get this error?

**Comment by Brunoandroid** [comment]
¿Has conseguido sacar este error?
