### ISSUE TITLE
Puedo usar checkout básico con este SDK-Android?

### ISSUE THREAD

**Issue by adeshjohnson** [mercadopago/sdk-android#19]
Puedo usar checkout básico en vez del personalizado (custom) con este SDK-Android?

**Comment by scirielli** [comment]
Con este SDK no.
Podes mirar este proyecto para sacar ideas:
https://github.com/volvin/MercadoPago-Checkout-Android-SDK

usa una webview para navegar el checkout web mobile. Son 3 o 4 clases que te podes llevar a tu proyecto.

Avisame si te sirve.

Sds,
SC

**Comment by adeshjohnson** [comment]
Hola:


Pues yo lo tengo implementado en un website. Quizás pueda usar Webviews, voy a ver.

Gracias por la sugerencia,

John Morales.

________________________________
