### ISSUE TITLE
Credentials not working

### ISSUE THREAD

**Issue by juanpjacob** [mercadopago/sdk-android#2]
I'm using the android-sdk in android studio and my credentials are not working. In my dependencies I added:
compile ('com.mercadopago:android-sdk:0.9.10@aar') { transitive = true }
As for the payment method, I'm using the credit card and using the sandbox credit card information.
I'm getting the message: 400 Bad Request with no information, so i don't know what is wrong

**Comment by scirielli** [comment]
Hi Juan,
about the credentials, do you mean your public key? could you update the issue with the code and the error you're receiving?
same with the payment method, add the code please so i can understand what's happening.

Regards,
SC

**Comment by norcasitas** [comment]
Hi, I'm using this sdk, but my credentials are not working, in ExampleUtils line 39, my public key (in mode sandbox) is TEST-55691604-9447-4817-8efd-c53ed23a685d (DUMMY_MERCHANT_PUBLIC_KEY) and these attributes :

    // * Merchant server vars
    public static final String DUMMY_MERCHANT_BASE_URL = "https://www.mercadopago.com";
    public static final String DUMMY_MERCHANT_GET_CUSTOMER_URI = "/checkout/examples/getCustomer";
    public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/checkout/examples/doPayment";
    //public static final String DUMMY_MERCHANT_GET_DISCOUNT_URI = "/checkout/examples/getDiscounts";

    // * Merchant access token
    public static final String DUMMY_MERCHANT_ACCESS_TOKEN = "mla-cards-data";

always returns me 400 bad request

I also tried to change the DUMMY_MERCHANT_ACCESS_TOKEN with my access token, but I think that the error is in DUMMY_MERCHANT_CREATE_PAYMENT_URI ,  this uri is right?

I'm trying to make a payment with com.mercadopago.examples.step1. 

Regards

**Comment by scirielli** [comment]
Ok. Right now our dummy server works only with the dummy merchant public key and not with your test public key. You should create your own server end-point, implement your business rules and validations, create a payment with a proper server-side SDK using your test private key.
Once your ok with your tests you can change it with your production key.

Regards,
SC

**Comment by laxmanvel** [comment]
Hi Scirielli,
I'm also using android SDK with PHP server side. But I couldn't understand what do you mean to told before. 

public static final String DUMMY_MERCHANT_BASE_URL = "https://www.mercadopago.com";

//Mine 
public static final String DUMMY_MERCHANT_BASE_URL = "https://www.mydomain.com";

Has above Base URL configured in mercadopago admin configuration or can we use our custom URL for Base URL?

public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/checkout/examples/doPayment";
//Mine
public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/mine/doPayment";

doPayment locate to what? Is there putting any server side code?

I have read from here for implement the Mercadopago payment. But I haven't got solutions from there. There is no good documentation for development. Is there any other way to get good documentation for Mercadopago?
https://www.mercadopago.com.ar/developers/en/solutions/payments/custom-checkout/charge-with-creditcard/android/

In the URL finally they shows server side code for doPayment function Am I right?

<?php
require_once ('mercadopago.php');

$mp = new MP('TEST-536715527243572-090820-e80a7e76627ef8a6fc5320252d7b23f3__LB_LD__-92582695'); //Sample Access Token

How can pass the below detail from my android code? these below payment data How can post android websevice to PHP server?
$payment_data = array(
	"transaction_amount" => 100, 
	"token" => "ff8080814c11e237014c1ff593b57b4d",
	"description" => "Title of what you are paying for",
	"installments" => 1,
	"payment_method_id" => "visa",
	"payer" => array (
		"email" => "test_user_19653727@testuser.com"
	)
);

$payment = $mp->post("/v1/payments", $payment_data);

?>

I am waiting for your kind response.

Regards,
LaxmanveL

**Comment by scirielli** [comment]
Hello,
i'll try to explain it step-by-step.

1) In Android and iOS SDKs we proposed a MerchantServer class to help you with the get customer cards and payment creation duties. Both tasks are resolved on your server and need your private key and validations. If you build your own experience using the pieces of code found in examples 1-4, you may use this class or you may build your own to send the Android data to your server. If you use the VaultActivity as seen in example 5 you must implement the MerchantServer class interaction;
2) MerchantServer class interaction assumes a POST call with 3 pieces:
- A MerchantPayment object to send to your server
- A Payment object received back as a response from the server
- Your server (PHP) Url;
3) MerchantPayment object is your client data to send to your server. It includes the payment method selected by the user (paymentMethodId, installments, cardToken, cardIssuerId), the item he is buying and a credential to identify the current app user on your server (merchantAccessToken);
4) Set the constants:
        public static final String MY_BASE_URL = "https://www.mydomain.com";
        public static final String MY_CREATE_PAYMENT_URI = "/mine/doPayment";
use them in the Merchant Server class. Place you PHP code there.
5) Now on your PHP code you should:
- Validate your app credential, check user identity, avoid illegal server calls
- Validate item data, id and unit_price. Maybe item stock
- Create the payment as found in the documentation, setting for example:
        "transaction_amount" => [item unit_price * quantity], 
        "token" => [MerchantPayment cardToken],
        "description" => [your item description],
        "installments" => [MerchantPayment installments],
        "payment_method_id" => [MerchantPayment paymentMethod],
        "payer" => array (
        "email" => [your user's email, found after identity check]
6) Finally, you can navigate a congrats activity showing some Payment class data. We provide a very simple one you may use calling:
        new MercadoPago.StartActivityBuilder()
                            .setActivity(activity)
                            .setPayment(payment)
                            .setPaymentMethod(paymentMethod)
                            .startCongratsActivity();
or you may copy/write a new one of your own.

Please let me know if it's a little bit clear or if i should explain something more.

Regards,
SC

PD: You're write about the poor documentation. Soon we'll update and improve the developers site docs as expected

**Comment by laxmanvel** [comment]
Hi Scirielli,

Thanks for your kind and useful response.

Still I am don't having knowledge in our Mercadopago payment. Here, What I have really done so far with Mercadopago payment. It may understand my issues. :)

In Android:

1) I have read your official documentation for android and successfully integrated Android sdk.
2) I have applied Example 1 from your documentation
3) By applying your test credentials,i.e Merchant_SERVER_URL,CREATE_PAYMENT_URI,Merchant public key and merchant access token,the create payment method works fine and its redirecting to congrats activity
4) But when I use my Merchant_BASE_URL="http://www.mydomain.com",Merchant public key="my public key",Merchant access token="my access token" I am getting my token and after when it goes to create payment method, I am getting error message 404 not found.
5) Ofcourse I understand,I have not implemented any php code on my server in CREATE_PAYMENT_URI i.e"/checkout/examples/doPayment" 
6) What should I do exactly in CREATE_PAYMENT_URI  to create my payment and redirect to congrats activity? 

In PHP:
Android device push to public static final String MY_CREATE_PAYMENT_URI = "/mine/doPayment";
//www.mydomain.com/mine/doPayment/

We have post values in PHP we can handle //www.mydomain.com/mine/doPayment/ But from Android we whould pass webservice for PHP servercoding like //www.mydomain.com/mine/doPayment?token=asdsadsadsd1212&etc

In your documentation shows:

https://www.mercadopago.com.ar/developers/en/solutions/payments/custom-checkout/charge-with-creditcard/android/

<?php
require_once ('mercadopago.php');

$mp = new MP('TEST-536715527243572-090820-e80a7e76627ef8a6fc5320252d7b23f3__LB_LD__-92582695');

$payment_data = array(
	"transaction_amount" => 100,
	"token" => "ff8080814c11e237014c1ff593b57b4d",
	"description" => "Title of what you are paying for",
	"installments" => 1,
	"payment_method_id" => "visa",
	"payer" => array (
		"email" => "test_user_19653727@testuser.com"
	)
);

$payment = $mp->post("/v1/payments", $payment_data);

Actually where I get these details from? In your create payment URI looks didn't passing any data on the URL( Webservice ). What will I do for?

I have been googling long time but I didn't have any good idea for our Mercadopago payment solutions. :(

For example if I create doPayment method for my domain.( I am using PHP CodeIgniter Framework )

In mydomain.com/mine/doPayment method I can use below code in PHP server.

<?php
require( APPPATH.'libraries/mercadopago/mercadopago.php');

$mp = new MP('My sand box access private key'); 

$payment_data = array(
	"transaction_amount" => $transactionAmount, 
	"token" => $cardToken,
	"description" => $title,
	"installments" => 1,
	"payment_method_id" => $paymentMethod,
	"payer" => array (
		"email" => $payerEmail
	)
);

$payment = $mp->post("/v1/payments", $payment_data);

We didn't pass data on the URL for doPayment then How can we get $transactionAmount, $cardToken, $paymentMethod and $payerEmail data for post payment to 'v1/payments'.

Important thing is what actually return from $payment variable?

Hope you understood my queries :) If anything else please contact me email also 
My email address: laxmanvel1994@gmail.com 

I really appreciate you for kind response, quick reply and more professional :) 

Thank in advance.

Regards,

LaxmanveL

**Comment by scirielli** [comment]
Hi,
Due to similar server-side misunderstandings we're going to publish our
getCustomer and doPayment PHP code soon (next week). I guess it should be
clear enough for you to understand how it works, and if it's not, you can
still ask me for more detail later.

Is that ok for you?

Regards,
Sergio

**Comment by laxmanvel** [comment]
Hi,
Thanks for your kind response. :)

Okay, But as I want to develop quickly not waiting for 1 week. understand my situation. actually I have one day for development. Can you please share updated PHP server code for Android SDK github repository. It will help me. :) Or send me invidiually that code. We have talked 3 more days but still I am having no idea for that. 

Hope, you can assist me on my queries. :)

Regards,
LaxmanveL

**Comment by scirielli** [comment]
Let's see if i can clarify.
When you call
```
MerchantServer.createPayment(activity, YOUR_BASE_URL, 
                                YOUR_CREATE_PAYMENT_URI, 
                                payment, callback);
```
you replace your base url and uri as you said with "https://mydomain.com" and "/mine/doPayment".
"payment" is a MerchantPayment including item, installments, cardIssuerId, token, paymentMethodId, campaignId and a token identifying the user in your app.
So far so good.
Then Android calls your server using Retrofit SDK, which creates this http request:
```
HTTP POST https://mydomain.com/mine/doPayment
Content-Type: application/json; charset=UTF-8
Content-Length: 313
{"campaign_id":null,"card_issuer_id":3,"card_token":"9e9099ff9c16e2377458ea827e205409","installments":1,"item":{"category_id":null,"currency_id":null,"description":null,"id":"id1","picture_url":null,"quantity":1,"title":null,"unit_price":100},"merchant_access_token":"mla-cards-data","payment_method_id":"master"}
```
You'll receive a similar JSON in your PHP code. From that point, you replace the values:
```
$payment_data = array(
"transaction_amount" => [is your item unit_price * quantity], 
"token" => [is the card_token field],
"description" => [is your item description],
"installments" => [is 1 in example 1, and for the rest the installments field],
"payment_method_id" => [is the payment_method_id field],
"payer" => array (
"email" => [once you resolve the merchant_access_token and discovered your user, is the user's email]
)
```
Finally don't forget to validate your item (id vs. unit_price, maybe stock) and your app user first (if merchant_access_token is a credential in your app, it should be a valid credential for example).

i hope this helps! let me know

Regards,
SC

**Comment by laxmanvel** [comment]
Hi Scirielli,
Thank you very much..! :) :) :+1: 
I have an idea from your response. $payment_data are from the POST method by android http request :)

I have last query in your reponse. Can you clarify it.  As you told that "Finally don't forget to validate your item (id vs. unit_price, maybe stock) and your app user first (if merchant_access_token is a credential in your app, it should be a valid credential for example)." Actually what do you mean by validate your item. Validations are already validate at Android mobile side SDK. Then finally what type of validation will validate?

Please, update your getCustomer php code also. Because I will develop do one time client used their creditcard details and next he just press a pay button and will pay automatically like Braintree creditcard payments method.

Nowadays all are hesitate to reenter their detail again in the payment section. So, I will try to do. Is it possible in MercadoPago? If yes, Can you please share documentation of that my queries related. :)

Thanks again :)

Regards,
LaxmanveL

**Comment by scirielli** [comment]
Hi,
about validations, think of your server-side end-point as a public api or service. If you have item 1 with a price of $20, someone could send a POST with a lower price and you will deliver it if you don't check price and id. And if your product is physical and not virtual you may also want to check for available stock.
We'll submit the server-side PHP code soon so you can see how de getCustomer controller works. You may also check out the Example 2 code included in the Android SDK showing the client side of the experience.

Regards,
SC

**Comment by scirielli** [comment]
Hi,
you can find the example code here: https://github.com/mercadopago/customcheckout-php-server
Check out the index.php and CheckoutController.class.php files.

I hope this helps a little more. 

Regards,
SC
