### ISSUE TITLE
Test Notificaciones Pagos

### ISSUE THREAD

**Issue by JavierSolis** [mercadopago/sdk-android#22]
Hola, como se hace para realizar un prueba de notificación de pago, por el tipo tycket, por ahora solo llego al paso de la reserva del pago, pero el deposito como se simula y la notificación de que se realizo el deposito del pago.

Gracias

**Comment by scirielli** [comment]
Hola Javier,
hoy todavía no tenemos pagos de prueba para tickets. No debería ser muy diferente a recibir un pago con tarjeta, sería revisar el medio de pago distinto nomas.

Saludos,
SC
