### ISSUE TITLE
CreateToken metodo Callback - Problema

### ISSUE THREAD

**Issue by Leanvitale** [mercadopago/sdk-android#24]
Buenos dias, tengo problema a la hora de generar el Token tanto para tarjetas nuevas como para tarjetas guardadas. Cito una seccion del codigo:

> private void createTokenAsync(CardToken cardToken) {

    LayoutUtil.showProgress(mActivity);

    mMercadoPago.createToken(cardToken, new Callback<Token>() {
        @Override
        public void success(Token token, Response response) {

            Intent returnIntent = new Intent();
            setResult(RESULT_OK, returnIntent);
            returnIntent.putExtra("token", token.getId());
            returnIntent.putExtra("paymentMethod", JsonUtil.getInstance().toJson(mPaymentMethod));
            finish();
        }

        @Override
        public void failure(ApiException apiException) {
	    //TODO: Manage API Failure
        }
    });
}

Cuando yo genero mi Callback, no tiene este formato, el mio solo incluye lo siguiente:

> mercadoPago.createToken(savedCardToken, new Callback<Token>() {
                @Override
                public void success(Token toke) {
                    token = toke;
                }
                @Override
                public void failure(ApiException apiException) {
                    ApiException error = apiException;
                    token = null;
                }
            });

Pero tengo el error de que no entra a la primera al Callback, me retorna null y luego vuelve al metodo y si entra. De esta manera el primero null que me trae me esta rompiendo el codigo.
Podrian decirme como es la forma correcta de obtener el token? Estoy viendo el codigo que hay de ejemplo pero no puedo hacerlo funcionar.
Saludos!

**Comment by matiasgualino** [comment]
@Leanvitale cómo estás? Te invitamos a seguir los pasos de este nuevo repo: github.com/mercadopago/px-android e inclusive guiarte por esta documentación: mercadopago.github.io/px-android/f1.html

Cualquier consulta por favor dejanos un issue en ese repositorio ya que este no tiene soporte.

Saludos,
Matias.
