### ISSUE TITLE
Plugin with id 'com.android.application' not found

### ISSUE THREAD

**Issue by mitultechs** [mercadopago/sdk-android#3]
Hey there,

 We have some issue in the running this source code in the android studio. We need to know which graddle version is compatible right now. 

ERROR FOUND WHILE SYNC:
Error:(1, 0) Plugin with id 'com.android.application' not found.

Do let me know how we can fix this issue. Looking to hear from you.

Mitul

**Comment by scirielli** [comment]
Hi Mitul,
i'm using gradle 2.2.1. do you have to update your project?

SC

**Comment by scirielli** [comment]
Now version 0.9.11 is using gradle 2.4.-
