### ISSUE TITLE
Erro "400 Bad Request"

### ISSUE THREAD

**Issue by guiffo** [mercadopago/sdk-android#6]
Estou tendo problemas ao alterar o public key.

Quando utilizo o app de exemplo que já vem com a public key definida:
DUMMY_MERCHANT_PUBLIC_KEY_BR = "APP_USR-f163b2d7-7462-4e7b-9bd5-9eae4a7f99c3"

Isso funciona normalmente, me retorna que o pagamento foi aprovado! 
Porém esse public key deve ser do SandBox de algum desenvolvedor do MP.

Quando altero o public Key para minha conta, tanto SandBox quanto produção eu recebo o erro: "400 Bad Resquest"

O SDK está realmente funcionando para outros usuários?
Qual seria a solução?

Obrigado,
Guilherme F.

**Comment by caducorrea** [comment]
Guilherme,

Sim, o SDK funciona para outros usuários.
O que acontece nesse caso, é que o mock server está implementado para os exemplos do SDK. 
Você precisa implementar o seu próprio server para fazer os pagamentos para o MercadoPago.

**Comment by guiffo** [comment]
Olá Cadu,

obrigado pela resposta.
Mas para clarear as idéias você pode explicar melhor? 

Eu li toda a documentação e não achei nada sobre isso!

Obrigado!

**Comment by caducorrea** [comment]
Essa é a documentação que mostra como fazer um pagamento:

https://www.mercadopago.com.br/developers/pt/solutions/payments/custom-checkout/charge-with-creditcard/android/

Veja no final da pagina, que há um curl que exemplifica o post do pagamento.

`curl -X POST \
        -H 'accept: application/json' \
        -H 'content-type: application/json' \
        'https://api.mercadopago.com/v1/payments?access_token=ACCESS_TOKEN' \
        -d '{
                "transaction_amount": 100,
                "token": "ff8080814c11e237014c1ff593b57b4d",
                "description": "Title of what you are paying for",
                "installments": 1,
                "payment_method_id": "visa",
                "payer": {
                        "email": "test_user_19653727@testuser.com"
                }
        }'`

Essa chamada deve ser feita a partir do seu back-end.

[]'s
