### ISSUE TITLE
Publicar los php

### ISSUE THREAD

**Issue by pfcvik** [mercadopago/sdk-android#7]
Hola queria ver si  es posible que publiquen los archivos php que utilizan en todo el ejemplo para procesar los pagos y los customers, es decir estos:

"/checkout/examples/getCustomer";
"/checkout/examples/doPayment";

Nos facilitaria mucho la integracion el poder tener ya esos archivos para subirlos a nuestro servidor y obviamente cambiando las credenciales correspondientes.

Saludos espero sea posible, ya que llevo una semana y no se como hacerlo!

**Comment by scirielli** [comment]
Hola,
estamos preparando este código ejemplo para subirlo al sitio en la brevedad (muy posiblemente a principios o mediados de la próxima semana).

Saludos,
SC

**Comment by pfcvik** [comment]
Hola Sergio.

Muchas gracias y estaré pendiente de cuando los suban ya que la aplicación
ya está terminada, incluso hasta las respuestas dependiendo de si el pago
fue exitoso. Sólo me faltan esos dos archivos para poner los pagos en
producción al igual que la app.

Saludos y gracias por su gran apoyo!

**Comment by scirielli** [comment]
Hola,
acá pueden encontrar el código ejemplo: https://github.com/mercadopago/customcheckout-php-server
Revisen los archivos index.php y CheckoutController.class.php.

Espero que deje las cosas más claras, sino seguiremos mejorándolo hasta que se entienda!

Saludos,
SC

**Comment by pfcvik** [comment]
Hola sergio esta roto el link

Gracias por tu ayuda!

**Comment by scirielli** [comment]
Que raro, yo lo veo bien:
https://github.com/mercadopago/customcheckout-php-server

**Comment by pfcvik** [comment]
No tendrá permisos o algo por el estilo?


2015-10-15 14:02 GMT-05:00 scirielli <notifications@github.com>:

**Comment by scirielli** [comment]
Eran permisos, ahora debería andar

**Comment by pfcvik** [comment]
Gracias veré los archivos!

**Comment by pfcvik** [comment]
Hola sergio ya revise los archivos pero aun no me queda claro como
implementarlos para mi proyecto en android, el doPayment.php lo puse de la
siguiente manera (archivo adjunto):

Espero me puedas apoyar Saludos!

**Comment by scirielli** [comment]
No estoy viendo el adjunto puede ser?
