### ISSUE TITLE
Creacion de item

### ISSUE THREAD

**Issue by benoffi7** [mercadopago/sdk-android#9]
El constructor de la clase **MerchantPayment** necesita un **Item**

 Item item = new Item(DUMMY_ITEM_ID, DUMMY_ITEM_QUANTITY,
                        DUMMY_ITEM_UNIT_PRICE);

Los items los crea el cliente de android o tienen que estar en algun otro lado?

**Comment by benoffi7** [comment]
Cuando le cambio el id a _pepe123-juan_ me dice

`bad_request invalid item unit_price`

el precio:

> public static final BigDecimal DUMMY_ITEM_UNIT_PRICE = new BigDecimal("1");

**Comment by scirielli** [comment]
Hola,
el objeto MerchantPayment es una representación del pago que viaja a tu servidor. La ponemos en el SDK para hacer más fácil la integración, pero podrías usar tu propio método. En el objeto Item podes poner los datos del producto que se quiere comprar, que después recibís y validas server-side.
Recordá que tenes que implementar tu propio servidor para postear el pago con tus credenciales privadas, el error que pasas después de bad request te lo da el mock server nuestro como prueba de validación.
Avisame si en algo no fui claro y te lo explico mejor.

Saludos

**Comment by omnixsolutions** [comment]
Buenas, se logro solucionar algo, yo tengo el mismo problema y no he podido resolver..

**Comment by scirielli** [comment]
Hola,
pudiste implementar tu propio código server-side? Como explicaba antes, estos errores son comportamiento de nuestro mock-server para ejemplos.

Saludos

**Comment by omnixsolutions** [comment]
ok,por aquí estoy, eso es lo que no he logrado hacer, en realidad no tengo mucha idea de como hacerlo, si tienes algún link o algo que me pueda ayudar con eso te lo sabria agradecer mucho

**Comment by scirielli** [comment]
En este link: https://github.com/mercadopago/customcheckout-php-server
podes encontrar un ejemplo de código server-side implementado en PHP. Sería llevar algo así a la tecnología que hayas elegido.
Avisame si necesitas algo más.

SC

**Comment by omnixsolutions** [comment]
Oook, muchas gracias, mi desarrollo es para una aplicación en android, con ese código en PHP, podría implementarlo y desde el codigo en la app Android llamarlo?

**Comment by scirielli** [comment]
Si, la idea es que llames a ese código PHP desde la app Android

**Comment by omnixsolutions** [comment]
Ok, muchas gracias.. ya estoy haciendo las pruebas a ver que resultados me dan y cualquier cosa, te estará comentado por si requiero otra orientación para poder terminar de implementar....

**Comment by omnixsolutions** [comment]
Ahh otra cosa que se me paso consultarte es esto, yo tengo mis varianles asi:

public static final String DUMMY_MERCHANT_BASE_URL = "https://www.mercadopago.com";
public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "http://omnixsolutions.com/pagos_app/customcheckout_server/doPayment";

no se si es la forma correcta.

**Comment by scirielli** [comment]
Sería:

public static final String DUMMY_MERCHANT_BASE_URL = "http://omnixsolutions.com";
public static final String DUMMY_MERCHANT_CREATE_PAYMENT_URI = "/pagos_app/customcheckout_server/doPayment";

y sería importante que sea HTTPS

**Comment by omnixsolutions** [comment]
ok.. lo coloque asi como me indicaste y me dio esto al tratar de procesar el pago:

Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

**Comment by omnixsolutions** [comment]
Disculpa de nuevo.. con solo.. copiar la programacion de este link: https://github.com/mercadopago/customcheckout-php-server

y colocar mi TOKEN es suficiente o hay que realizar otros ajustes?

en esto de la programacion en PHP soy nuevo.

**Comment by scirielli** [comment]
Fijate que en la clase:
https://github.com/mercadopago/customcheckout-php-server/blob/master/CheckoutController.class.php

está bien documentado el paso a paso y los ajustes que tenes que hacer. No es solo el token, sino cuotas, medio de pago, etc.

Sds,
SC

**Comment by dangarit** [comment]
Hola tengo este mismo error
 JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
y no lo he podido solucionar, como lo solucionaste?
